### ISSUE TITLE
Support for Enums

### ISSUE THREAD

**Issue by Mehni** [AaronCRobinson/ModWindowHelper#1]
Goal: allow usage of enums in the settings. Best implemented as radiobuttons, cases of a slider would be nice to have (see: quality settings. Example which sorta implements this: it https://github.com/RimWorld-CCL-Reborn/4M-Mehni-s-Misc-Modifications/blob/Unstable-1.0/Mehni's%20Misc%20Modifications/Settings.cs#L186 )

Will need to translate enum values to string as well.

**Comment by AaronCRobinson** [comment]
Should be a viable implementation in commit ae6b1ee9fdaf8a67068cdad632a7a3becd78bde5. Let me know and we can close this out.

**Comment by Mehni** [comment]
This looks good. Thanks WIT.
